INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT) VALUES (100001,'USD','INR',85,0);
INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT) VALUES (100002,'EURO','INR',65,0);
INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT) VALUES (100003,'POUND','INR',75,0);
INSERT INTO EXCHANGE_VALUE (ID, CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT) VALUES (100004,'DIRHAM','INR',95,0);